version: '3.8'

services:
  postgres:
    image: postgres:14.4
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: njidda
    ports:
      - "5431:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

  mysql:
    image: mysql:8.2.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: njidda
    ports:
      - "3308:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  mariadb:
    image: mariadb:latest
    container_name: mariadb-db
    environment:
      MYSQL_ROOT_PASSWORD: njidda
    ports:
      - "3307:3306"
    volumes:
      - mariadbdata:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: njidda
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

volumes:
  postgresdata:
  mysqldata:
  mariadbdata:
  mongodbdata:
